# docs: <https://golangci-lint.run/usage/configuration/>

run:
  timeout: "5m"

linters:
  enable:
    - errorlint
    - gci
    - gocritic
    - gofmt

linters-settings:
  funlen:
    lines: 120
    statements: 120
  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
  gci:
    sections:
      - standard
      - default
      - prefix(k8s.io,sigs.k8s.io)
      - prefix(github.com/nobbs)

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - dupl
        - unused
