# docs: <https://golangci-lint.run/usage/configuration/>
linters:
  enable:
    - gofmt
    - gci
    - errorlint
    - dogsled
    - nilnil
    - funlen
    - dupl
    - gocritic

linters-settings:
  funlen:
    lines: 120
    statements: 120
  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
