version: "3"

vars:
  GOPATH:
    sh: go env GOPATH

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: Run tests and linter
    cmds:
      - task: test
      - task: lint

  build:
    desc: Build the binary
    cmds:
      - go build -buildvcs=true -o bin/kubectl-mapr_ticket ./
    sources:
      - ./**/*.go
    generates:
      - bin/kubectl-mapr_ticket

  test:
    desc: Run tests
    cmds:
      - |
        export PATH=$PATH:$(go env GOPATH)/bin
        gotestsum --  -coverprofile=coverage.txt -covermode=atomic ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  lint:fix:
    desc: Run linter with auto-fix enabled
    cmds:
      - golangci-lint run --fix

  pre-commit:
    desc: Run pre-commit checks
    cmds:
      - pre-commit run --all-files

  install:gotestsum:
    desc: Install gotestsum
    cmds:
      - go install gotest.tools/gotestsum@latest
